apache/incubator-devlake-helm-chart

.asf.yaml

Fix close features

---

.github/workflows/deploy-test.yml
.github/workflows/yaml-lint.yml
charts/devlake/Chart.yaml
charts/devlake/README.md
charts/devlake/templates/_helpers.tpl
charts/devlake/templates/configmaps.yaml
charts/devlake/templates/deployments.yaml
charts/devlake/templates/ingresses.yaml
charts/devlake/templates/services.yaml
charts/devlake/templates/statefulsets.yaml
charts/devlake/values.yaml

This PR tries to provide helm deployment with PostgreSQL as a database or use external PostgreSQL.
Fixes Issue: https://github.com/apache/incubator-devlake/issues/3544

Add support postgres database.

---

charts/devlake/README.md
charts/devlake/templates/configmaps.yaml
charts/devlake/templates/statefulsets.yaml
charts/devlake/values.yaml

Support setting log level in helm chart to enable debug log for debugging some issues

feat(helm): Support setting log level in helm chart

---

charts/devlake/templates/deployments.yaml
charts/devlake/templates/statefulsets.yaml
charts/devlake/values.yaml

There are resources/nodeSelector/affinity/tolerations config in values.yaml but no used in related yamls

feat(helm): Support resources/nodeSelector/affinity/tolerations properties for lake/ui/grafana

---

charts/devlake/Chart.yaml
charts/devlake/values.yaml

udpate version

---

charts/devlake/Chart.yaml
charts/devlake/README.md
charts/devlake/templates/statefulsets.yaml
charts/devlake/values.yaml

- Need refactorying env config later
Signed-off-by: Ji Bin <matrixji@live.com>

Workaround for API_REQUESTS_PER_HOUR

---

charts/devlake/values.yaml

fix(image version): change to v0.15.0-rc4

---

.github/workflows/lint-image-chart-versions.yml
README.md
charts/devlake/Chart.yaml
charts/devlake/templates/deployments.yaml
charts/devlake/templates/statefulsets.yaml
charts/devlake/values.yaml

udpate to v0.15.1-beta3

---

charts/devlake/Chart.yaml
charts/devlake/values.yaml

update helm tag to v0.15.0 official release version

update helm tag to v0.15.0 official release version

---

README.md

This doc add a guide `How to upgrade chart version`

doc-how-to-upgrade-chart

---

charts/devlake/Chart.yaml
charts/devlake/values.yaml

feat: upgrade helm chart for v0.16.0-beta6

feat: upgrade helm chart for v0.16.0-beta6

---

charts/devlake/Chart.yaml
charts/devlake/values.yaml

upgrade helm chart for v0.16.0-beta8

feat: upgrade helm chart for v0.16.0-beta8

---

HelmSetup.md
charts/devlake/Chart.yaml
charts/devlake/templates/configmaps.yaml
charts/devlake/templates/deployments.yaml
charts/devlake/templates/ingresses.yaml
charts/devlake/templates/services.yaml
charts/devlake/values.yaml

feat: optional grafana install

---

README.md

docs: upgrade helm chart doc for v0.16.0-beta10

docs: upgrade helm chart doc for v0.16.0-beta10

---

README.md
charts/devlake/Chart.yaml
charts/devlake/values.yaml

feat: upgrade helm chart doc for v0.16.0-beta11

feat: upgrade helm chart doc for v0.16.0-beta11

---

charts/devlake/templates/configmaps.yaml
charts/devlake/templates/deployments.yaml
charts/devlake/values.yaml

modify configmap to support configuring aws keys

feat(configui): modify configmap to support aws keys

---

charts/devlake/templates/configmaps.yaml

Update cloud service

---

README.md
charts/devlake/Chart.yaml
charts/devlake/values.yaml

feat: upgrade helm chart doc for v0.16.0-beta13

feat: upgrade helm chart doc for v0.16.0-beta13

---

charts/devlake/Chart.yaml
charts/devlake/values.yaml

feat: update helm version v0.17.0-beta3

---

.github/workflows/release.yaml

cherry pick https://github.com/apache/incubator-devlake-helm-chart/pull/151

make release-v* branch trigger publishing of stable version (#151)

---

charts/devlake/values.yaml

cherry pick https://github.com/apache/incubator-devlake-helm-chart/pull/143 to release-v0.17

feat: use Scarf Gateway for DevLake helm charts downloads (#143)

---

.github/workflows/release.yaml
.gitmodules

Reverts apache/incubator-devlake-helm-chart#201

Revert "Replace submodules by GitHub actions"

---

.github/workflows/release.yaml

fix: index.yaml not found

---

HelmSetup.md
README.md
charts/devlake/Chart.yaml
charts/devlake/values.yaml

Update to v0.20.0 beta4

---

HelmSetup.md
README.md
charts/devlake/Chart.yaml
charts/devlake/values.yaml

https://hub.docker.com/layers/apache/devlake/v0.18.1-beta3/images/sha256-e55a3f5e24523895bd40d31d1456e87fda88b1c0224c0e5112f57672a1e1d504?context=explore

adjust to v0.18.1-beta3

---

HelmSetup.md
charts/devlake/templates/deployments.yaml
charts/devlake/values.yaml

feat: add liveness and readiness probe for ui

---

HelmSetup.md
charts/devlake/templates/deployments.yaml
charts/devlake/values.yaml

close https://github.com/apache/incubator-devlake-helm-chart/issues/227

add probes for config ui

---

charts/devlake/templates/deployments.yaml

fix: add devlakeComponent as selector label

---

charts/devlake/templates/statefulsets.yaml

This PR is similar to https://github.com/apache/incubator-devlake-helm-chart/pull/245 where I'd like to add support for `imagePullSecrets` also in database StatefulSet.

Add support for `imagePullSecrets` in database StatefulSet

---

charts/devlake/templates/ingresses.yaml

Reverts apache/incubator-devlake-helm-chart#272

Revert "fix: use pathType ImplementationSpecific for regex"

---

charts/devlake/templates/deployments.yaml
charts/devlake/values.yaml

added extraContainer to the ui section

add extra container to ui stanza

---

charts/devlake/templates/ingresses.yaml
charts/devlake/templates/services.yaml
charts/devlake/values.yaml

This PR adds the possibility to add custom additional labels in services and ingress.
Closes #322

[Feature]: Configure extraLables in services and ingress

---

charts/devlake/Chart.yaml
charts/devlake/values.yaml

fix devlake images still use beta7 after upgrade

V1.0.2 beta8 fix
