.github/workflows/lint-image-chart-versions.yml
A few weeks ago, we build a chart release with wrong images. So  we add this `ci` to check if image versions are equal to chart version.
We separate this `ci` from lint-chart-versions.yml because when we use version with `rc` tag we cannot pass lint-chart-versions.yml
=> test(ci): add ci to check image version and chart version

charts/devlake/templates/ingresses.yaml, charts/devlake/values.yaml
If `.Values.ingress.useDefaultNginx` is false, then the Nginx-specific parts of the code are removed, and you're left with a generic ingress. This value is true by default.
If `.Values.grafana.useExternal` and `.Values.ingress.useDefaultNginx` are true, then it creates an Nginx redirect ingress.
=> feat: enable selection of default Nginx ingress vs generic one.

charts/devlake/templates/statefulsets.yaml
$ kg pod
```sh
NAME                               READY   STATUS    RESTARTS   AGE
devlake-grafana-66fb6f4b5c-vll9t   1/1     Running   0          91s
devlake-lake-0                     1/1     Running   0          9s
devlake-mysql-0                    1/1     Running   0          91s
devlake-ui-68c89ccbff-ghft9        1/1     Running   0          91s
```
I've test this change locally.
- MySQL Dockerfile
- entrypoint -> command
- cmd -> args
=> feat: add some args to mysql container

.asf.yaml
I get a lot of duplicate emails from Github(notification@github.com) and ASF mailing list (dev@devlake.apache.org) of the repo which is confusing and unnecessary.
This PR redirects commits/issues/prs notifications sent by ASF to another mailing list commits@devlake.apache.org to avoid the duplication.
=> chore: avoid sending notification to dev@devlake.apache.org

HelmSetup.md, charts/devlake/templates/deployments.yaml, charts/devlake/templates/secrets.yaml, charts/devlake/templates/statefulsets.yaml, charts/devlake/values.yaml
This pull request allows adding **security context** to both pod and containers in all the deployments/statefulsets. 
@matrixji @klesh @IronCore864 Kindly take a look :)
=> Feat: include security context

charts/devlake/values.yaml
When using the MySQL prepared by DevLake, you can specify a root password to manage the MySQL.
@klesh @matrixji Please take a look. cc @JorgeGar @hezyin
=> fix: repair comment error.

charts/devlake/templates/grafana-dashboard-configmaps/bitbucket.yaml, charts/devlake/templates/grafana-dashboard-configmaps/componentandfilelevelmetrics.yaml, charts/devlake/templates/grafana-dashboard-configmaps/contributorexperience.yaml, charts/devlake/templates/grafana-dashboard-configmaps/demoaveragerequirementleadtimebyassignee.yaml, charts/devlake/templates/grafana-dashboard-configmaps/democommitcountbyauthor.yaml, charts/devlake/templates/grafana-dashboard-configmaps/demodetailedbuginfo.yaml, charts/devlake/templates/grafana-dashboard-configmaps/demohomepage.yaml, charts/devlake/templates/grafana-dashboard-configmaps/demohowfastdowerespondtocustomerrequirements.yaml, charts/devlake/templates/grafana-dashboard-configmaps/demoisthismonthmoreproductivethanlast.yaml, charts/devlake/templates/grafana-dashboard-configmaps/demowasourqualityimprovedornot.yaml, charts/devlake/templates/grafana-dashboard-configmaps/dora.yaml, charts/devlake/templates/grafana-dashboard-configmaps/dorabyteam.yaml, charts/devlake/templates/grafana-dashboard-configmaps/doradebug.yaml, charts/devlake/templates/grafana-dashboard-configmaps/engineeringoverview.yaml, charts/devlake/templates/grafana-dashboard-configmaps/engineeringthroughputandcycletime.yaml, charts/devlake/templates/grafana-dashboard-configmaps/engineeringthroughputandcycletimeteamview.yaml, charts/devlake/templates/grafana-dashboard-configmaps/github.yaml, charts/devlake/templates/grafana-dashboard-configmaps/githubreleasequalityandcontributionanalysis.yaml, charts/devlake/templates/grafana-dashboard-configmaps/gitlab.yaml, charts/devlake/templates/grafana-dashboard-configmaps/homepage.yaml, charts/devlake/templates/grafana-dashboard-configmaps/jenkins.yaml, charts/devlake/templates/grafana-dashboard-configmaps/jira.yaml, charts/devlake/templates/grafana-dashboard-configmaps/sonarqube.yaml, charts/devlake/templates/grafana-dashboard-configmaps/tapd.yaml, charts/devlake/templates/grafana-dashboard-configmaps/teambition.yaml, charts/devlake/templates/grafana-dashboard-configmaps/weeklybugretro.yaml, charts/devlake/templates/grafana-dashboard-configmaps/weeklycommunityretro.yaml, charts/devlake/templates/grafana-dashboard-configmaps/zentao.yaml
Otherwise the configmap cause conflicts if multiple chart releases are installed in the same kubernetes namespace.
=> fix: Use devlake.fullname in dashboard configmaps

HelmSetup.md, charts/devlake/templates/statefulsets.yaml, charts/devlake/values.yaml
@JorgeGar Do I need to also add the specific initContainer configs solution to #194 to this PR or leave it customizable as is?
=> Add initContainer in statefulsets and values

charts/devlake/templates/deployments.yaml, charts/devlake/templates/statefulsets.yaml, charts/devlake/values.yaml
Hi!
My team has recently adopted `devlake` and have found ourselves unable to monitor the kubernetes resources effectively without annotations.  So that's what this pull request is intended to add.
=> adding ability to leverage basic annotations

charts/devlake/templates/deployments.yaml, charts/devlake/templates/ingresses.yaml
Two issues I ran into while using the chart
- Ingress backend service for `grafana` is misconfigured, both name and port
#160
- Unable to set `containerSecurityContext` for `devlake-backend` due to indentation problem
=> fix: Grafana ingress and containerSecurity

.github/workflows/release.yaml, .gitmodules
Currently `Helm release` builds are [failing](https://github.com/apache/incubator-devlake-helm-chart/actions/runs/6862648484) due to submodules problems
This PR addresses this by replacing the submodules by direct action references
=> Replace submodules by GitHub actions

HelmSetup.md, charts/devlake/templates/deployments.yaml, charts/devlake/values.yaml
Hey everyone,
my company has some K8s cluster policies in place that require me to set certain metadata labels. So far it's not possible to configure this in the Helm chart. That's why I'd like to propose this change.
Cheers
=> feat: add additional deployment metadata labels

HelmSetup.md, charts/devlake/templates/deployments.yaml, charts/devlake/values.yaml
Fix : https://github.com/apache/incubator-devlake-helm-chart/issues/231
=> Add imagepullsecrets

charts/devlake/templates/_helpers.tpl, charts/devlake/templates/deployments.yaml
If setting `.ui.basicAuth.enabled: true`, `ui.readinessProbe` and `ui.livenessProbe` :x: fail because the `httpGet` probe replies with `HTTP 401`.
If no `httpHeaders` are added manually in values (to add `Authorization` header), define them based on the `basicAuth.user` and `basicAuth.password` value.
=> feat: add authorization to health probes

charts/devlake/values.yaml
ebs pvc can only be mounted on one server
=> adjust grafana update policy

charts/devlake/templates/ingresses.yaml
fix error
```
path /(/?|$)(.*) cannot be used with pathType Prefix
```
=> fix: use pathType ImplementationSpecific for regex

charts/devlake/values.yaml
Deploying the helmchart v0.21 (latest stable release to date), I've experienced a grafana redirect loop error (ERR_TOO_MANY_REDIRECTS). 
With this change on helm's values, the problem was gone.
Opened an issue: https://github.com/apache/incubator-devlake-helm-chart/issues/283
This PR fixes this problem.
However, as stated in the issue comments, @ZhangNing10 told me this "Serve from subpath" problem, should be an environment variable as it is declared on the Dockerfile (https://github.com/apache/incubator-devlake/commit/d52abffb6579b4231c7c587822a69d9cc6f7d043). However the version of the image i'm using does not include that.
=> Fix Grafana redirect loop

charts/devlake/templates/deployments.yaml, charts/devlake/values.yaml
The devlake [Deployment](https://github.com/apache/incubator-devlake-helm-chart/blob/1b9a97f4a4c103d62c0f9a4ccdf9afc39b9c5307/charts/devlake/templates/deployments.yaml#L121) does not expose `Volumes`, `VolumeMounts`.
These are required e.g. to mount a CA Certificate to establish a secure SSL connection.
Our policies only allow SSL connections to Azure MySQL Server. I would love to contribute to Apache DevLAke and add the PR myself.
There are several GH issues related to SSL and the current limitations
- https://github.com/apache/incubator-devlake/issues/7928
- https://github.com/apache/incubator-devlake/issues/8121
See  #310
=> Enable option to add Volume, VolumeMount to devlake Deployment - critical for SSL certificate

charts/devlake/templates/extraresources.yaml, charts/devlake/values.yaml
Hello there. I have added `extraResources` section into values as it's super useful in some scenarios needing credentials defined as ExternalSecret objects, or exposing devlake using HTTPRoute objects instead of Ingress.
WDYT? I think this is a little change but super useful :)  
CC: @abeizn @ZhangNing10
=> feat: Add extraResources section

charts/devlake/templates/services.yaml, charts/devlake/values.yaml
This PR enhances the Helm chart by adding support for the LoadBalancer service type and allowing users to configure loadBalancerIP in values.yaml.
Changes:
✅ values.yaml
- Added LoadBalancer as an option for service.type
- Introduced service.loadBalancerIP (optional)
✅ templates/service.yaml
- Applied LoadBalancer configuration when service.type is set to LoadBalancer
- Set loadBalancerIP only if a value is provided
=> Support LoadBalancer service type and configurable loadBalancerIP

.github/workflows/release.yaml, README.md
Fix #317 (more details there)
Provide chart as OCI artifact on GHCR 
I've tested the workflow changes on my fork: https://github.com/jonesbusy/incubator-devlake-helm-chart/actions/runs/12741995690
=> OCI distribution

charts/devlake/templates/statefulsets.yaml, charts/devlake/values.yaml
This is a PR for issue [333](https://github.com/apache/incubator-devlake-helm-chart/issues/333).
With this, users will be able to more easily append additional args for MySQL.
=> Adding Mysql extraArgs to values.yaml

.github/workflows/smoke-test.yml, charts/devlake/templates/_helpers.tpl, charts/devlake/templates/configmap.yaml, charts/devlake/templates/deployments.yaml, charts/devlake/templates/statefulsets.yaml, charts/devlake/values.yaml
Fixes #340 #349
1. **Extensible & overridable MySQL DB URL**
* New value: `mysql.extraParams` (e.g., `&tls=skip-verify`), appended to the generated DSN.
* New value: `option.assembleDbUrl` (default `true`). When set to `false`, the chart **skips** auto-assembly so users can supply `DB_URL` via `lake.envs` or an external Secret/ConfigMap.
* Plumbs `DB_CUSTOM_PARAMS` via ConfigMap to keep env composition explicit.
2. **Grafana datasource picks up MySQL envs**
* Adds `option.connectionConfigmapName` and wires it into `grafana.extraEnvFrom`, ensuring the `MYSQL_*` envs are visible to Grafana for the DevLake datasource initialization.
* Keeps the default name stable, but allows overriding where installations differ.
3. **New GitHub Actions smoke-test (repro & prevention)**
* Spins up a …
=> helm: make MySQL `DB_URL` extensible/overridable, wire Grafana datasource envs, and add smoke-test CI

.github/workflows/smoke-test.yml
Our release workflow was failing because Apache Policy doesn't allow 3rd party actions.
See: https://github.com/apache/incubator-devlake-helm-chart/actions/runs/17422005314
- Removed 3rd party actions dependencies.
- Added explicit installation steps for:
- kubectl (latest stable)
- Helm (v3.x)
- kind (v0.x)
- Updated workflow to create the kind cluster and run the same chart tests as before.
https://github.com/kahirokunn/incubator-devlake-helm-chart/actions/runs/17422902615/job/49464563027
=> Replace helm/kind-action with manual kind/Helm/kubectl setup in CI
